version: '3.9'

services:
  app:
    image: node:14-slim
    command: npm run start:dev
    env_file:
      - .env
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
